Repository softvenue/i18n, pull requests merged in 2019-08, with the labels that each got.

#17 Update .gitignore
  .gitignore
Labels: i18n

#21 New Design
  css/main.css
  index.html
  js/main.js
Labels: website

#20 Create 404 page
  404.html
Labels: website

#22 add new term: vulnerablility
  i18n.json
Labels: i18n

#25 Update .gitlab-ci.yml
  .gitlab-ci.yml
Labels: i18n

#23 Update the website : light facelift
  css/main.css
  index.html
  js/main.js
Labels: enhancement, website

#24 update file - i18n.json
  i18n.json
Labels: New Term, i18n

#32 Add pull request template 🗺 ..
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#30 add LICENSE 🔏 ..
  LICENSE
Labels: miscellaneous

#38 Config subdomain i18n.softvenue.net
  CNAME
Labels: enhancement, website
